-- MySQL Script generated by MySQL Workbench
-- Thu May 15 21:48:57 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbproj
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbproj` ;

-- -----------------------------------------------------
-- Schema dbproj
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbproj` DEFAULT CHARACTER SET utf8 ;
USE `dbproj` ;

-- -----------------------------------------------------
-- Table `dbproj`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbproj`.`User` ;

CREATE TABLE IF NOT EXISTS `dbproj`.`User` (
  `idUser` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `passw` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `birthday` DATE NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproj`.`ProductCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbproj`.`ProductCategory` ;

CREATE TABLE IF NOT EXISTS `dbproj`.`ProductCategory` (
  `idProductCategory` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `descript` VARCHAR(200) NULL,
  PRIMARY KEY (`idProductCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproj`.`ProductRarity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbproj`.`ProductRarity` ;

CREATE TABLE IF NOT EXISTS `dbproj`.`ProductRarity` (
  `idProductRarity` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(200) NULL,
  `duration` INT NULL,
  PRIMARY KEY (`idProductRarity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproj`.`Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbproj`.`Game` ;

CREATE TABLE IF NOT EXISTS `dbproj`.`Game` (
  `idGame` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `developer` VARCHAR(45) NULL,
  PRIMARY KEY (`idGame`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproj`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbproj`.`Product` ;

CREATE TABLE IF NOT EXISTS `dbproj`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `idProductCategory` INT NOT NULL,
  `idProductRarity` INT NOT NULL,
  `idGame` INT NOT NULL,
  `imgURL` VARCHAR(200) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `salePrice` FLOAT NULL,
  `rentPrice` FLOAT NULL,
  PRIMARY KEY (`idProduct`),
  INDEX `product_productCategory_idx` (`idProductCategory` ASC) VISIBLE,
  INDEX `product_productRarity_idx` (`idProductRarity` ASC) VISIBLE,
  INDEX `product_game_idx` (`idGame` ASC) VISIBLE,
  CONSTRAINT `product_productCategory`
    FOREIGN KEY (`idProductCategory`)
    REFERENCES `dbproj`.`ProductCategory` (`idProductCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_productRarity`
    FOREIGN KEY (`idProductRarity`)
    REFERENCES `dbproj`.`ProductRarity` (`idProductRarity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_game`
    FOREIGN KEY (`idGame`)
    REFERENCES `dbproj`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproj`.`Sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbproj`.`Sale` ;

CREATE TABLE IF NOT EXISTS `dbproj`.`Sale` (
  `idSale` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT UNSIGNED NOT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`idSale`),
  INDEX `sale_user_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `sale_user`
    FOREIGN KEY (`idUser`)
    REFERENCES `dbproj`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproj`.`Discount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbproj`.`Discount` ;

CREATE TABLE IF NOT EXISTS `dbproj`.`Discount` (
  `idDiscount` INT NOT NULL AUTO_INCREMENT,
  `idProduct` INT NOT NULL,
  `discount` INT NOT NULL,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  PRIMARY KEY (`idDiscount`),
  INDEX `discount_product_idx` (`idProduct` ASC) VISIBLE,
  CONSTRAINT `discount_product`
    FOREIGN KEY (`idProduct`)
    REFERENCES `dbproj`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproj`.`SaleDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbproj`.`SaleDetail` ;

CREATE TABLE IF NOT EXISTS `dbproj`.`SaleDetail` (
  `idSale` INT NOT NULL,
  `idProduct` INT NOT NULL,
  `price` FLOAT NULL,
  `idDiscount` INT NULL,
  PRIMARY KEY (`idSale`, `idProduct`),
  INDEX `sellDetail_product_idx` (`idProduct` ASC) VISIBLE,
  INDEX `saleDetail_discount_idx` (`idDiscount` ASC) VISIBLE,
  CONSTRAINT `saleDetail_product`
    FOREIGN KEY (`idProduct`)
    REFERENCES `dbproj`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `saleDetail_sale`
    FOREIGN KEY (`idSale`)
    REFERENCES `dbproj`.`Sale` (`idSale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `saleDetail_discount`
    FOREIGN KEY (`idDiscount`)
    REFERENCES `dbproj`.`Discount` (`idDiscount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproj`.`Rent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbproj`.`Rent` ;

CREATE TABLE IF NOT EXISTS `dbproj`.`Rent` (
  `idRent` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT UNSIGNED NOT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`idRent`),
  INDEX `rent_user_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `rent_user`
    FOREIGN KEY (`idUser`)
    REFERENCES `dbproj`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproj`.`RentDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbproj`.`RentDetail` ;

CREATE TABLE IF NOT EXISTS `dbproj`.`RentDetail` (
  `idRent` INT NOT NULL,
  `idProduct` INT NOT NULL,
  `price` FLOAT NULL,
  PRIMARY KEY (`idRent`, `idProduct`),
  INDEX `rentDetail_product_idx` (`idProduct` ASC) VISIBLE,
  CONSTRAINT `rentDetail_product`
    FOREIGN KEY (`idProduct`)
    REFERENCES `dbproj`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rentDetail_rent`
    FOREIGN KEY (`idRent`)
    REFERENCES `dbproj`.`Rent` (`idRent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
