-- MySQL Script generated by MySQL Workbench
-- Thu May  1 18:23:16 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proj
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proj
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proj` DEFAULT CHARACTER SET utf8 ;
USE `proj` ;

-- -----------------------------------------------------
-- Table `proj`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proj`.`User` (
  `idUser` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `birthday` DATE NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proj`.`ProductCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proj`.`ProductCategory` (
  `idProductCategory` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `Description` VARCHAR(200) NULL,
  PRIMARY KEY (`idProductCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proj`.`ProductRarity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proj`.`ProductRarity` (
  `idProductRarity` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(200) NULL,
  `duration` INT NULL,
  PRIMARY KEY (`idProductRarity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proj`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proj`.`Product` (
  `idProduct` INT NOT NULL,
  `imgURL` VARCHAR(200) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `idProductCategory` INT NULL,
  `idProductRarity` INT NULL,
  `SalePrice` FLOAT NULL,
  `discount` INT NULL,
  `RentPrice` FLOAT NULL,
  PRIMARY KEY (`idProduct`),
  INDEX `product_productCategory_idx` (`idProductCategory` ASC) VISIBLE,
  INDEX `product_productRarity_idx` (`idProductRarity` ASC) VISIBLE,
  CONSTRAINT `product_productCategory`
    FOREIGN KEY (`idProductCategory`)
    REFERENCES `proj`.`ProductCategory` (`idProductCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_productRarity`
    FOREIGN KEY (`idProductRarity`)
    REFERENCES `proj`.`ProductRarity` (`idProductRarity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proj`.`Sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proj`.`Sale` (
  `idSale` INT NOT NULL,
  `idUser` INT UNSIGNED NOT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`idSale`),
  INDEX `sale_user_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `sale_user`
    FOREIGN KEY (`idUser`)
    REFERENCES `proj`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proj`.`Discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proj`.`Discount` (
  `idDiscount` INT NOT NULL,
  `idProduct` INT NOT NULL,
  `discount` INT NOT NULL,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  PRIMARY KEY (`idDiscount`),
  INDEX `discount_product_idx` (`idProduct` ASC) VISIBLE,
  CONSTRAINT `discount_product`
    FOREIGN KEY (`idProduct`)
    REFERENCES `proj`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proj`.`SaleDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proj`.`SaleDetail` (
  `idSale` INT NOT NULL,
  `idProduct` INT NOT NULL,
  `price` FLOAT NULL,
  `idDiscount` INT NULL,
  PRIMARY KEY (`idSale`, `idProduct`),
  INDEX `sellDetail_product_idx` (`idProduct` ASC) VISIBLE,
  INDEX `saleDetail_discount_idx` (`idDiscount` ASC) VISIBLE,
  CONSTRAINT `saleDetail_product`
    FOREIGN KEY (`idProduct`)
    REFERENCES `proj`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `saleDetail_sale`
    FOREIGN KEY (`idSale`)
    REFERENCES `proj`.`Sale` (`idSale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `saleDetail_discount`
    FOREIGN KEY (`idDiscount`)
    REFERENCES `proj`.`Discount` (`idDiscount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proj`.`Rent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proj`.`Rent` (
  `idRent` INT NOT NULL,
  `idUser` INT UNSIGNED NOT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`idRent`),
  INDEX `rent_user_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `rent_user`
    FOREIGN KEY (`idUser`)
    REFERENCES `proj`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proj`.`RentDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proj`.`RentDetail` (
  `idRent` INT NOT NULL,
  `idProduct` INT NOT NULL,
  `price` FLOAT NULL,
  PRIMARY KEY (`idRent`, `idProduct`),
  INDEX `rentDetail_product_idx` (`idProduct` ASC) VISIBLE,
  CONSTRAINT `rentDetail_product`
    FOREIGN KEY (`idProduct`)
    REFERENCES `proj`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rentDetail_rent`
    FOREIGN KEY (`idRent`)
    REFERENCES `proj`.`Rent` (`idRent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
